# Generated by Django 4.2.3 on 2023-10-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestiveQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('answer', models.CharField(blank=True, max_length=255, null=True)),
                ('marked_for_removal', models.BooleanField(default=False)),
            ],
        ),
    ]
