# Generated by Django 4.2.6 on 2023-11-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestiveQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('marked_for_removal', models.BooleanField(default=False)),
                ('is_added_to_qa_dataset', models.BooleanField(default=False)),
            ],
        ),
    ]
