# Generated by Django 4.2.3 on 2023-10-04 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QADataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bangla_ques', models.CharField(max_length=255, verbose_name='Bangla Question')),
                ('english_ques', models.CharField(max_length=255, verbose_name='English Question')),
                ('transliterated_ques', models.CharField(max_length=255, verbose_name='Transliterated (Banglish) Question')),
                ('bangla_ans', models.CharField(max_length=255, verbose_name='Bangla Answer')),
                ('english_ans', models.CharField(max_length=255, verbose_name='English Answer')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
        ),
    ]
