# Generated by Django 4.2.6 on 2024-01-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qaDatasetApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qadataset',
            name='bangla_ans',
            field=models.TextField(verbose_name='Bangla Answer'),
        ),
        migrations.AlterField(
            model_name='qadataset',
            name='bangla_ques',
            field=models.TextField(verbose_name='Bangla Question'),
        ),
        migrations.AlterField(
            model_name='qadataset',
            name='english_ans',
            field=models.TextField(verbose_name='English Answer'),
        ),
        migrations.AlterField(
            model_name='qadataset',
            name='english_ques',
            field=models.TextField(verbose_name='English Question'),
        ),
        migrations.AlterField(
            model_name='qadataset',
            name='transliterated_ques',
            field=models.TextField(verbose_name='Transliterated (Banglish) Question'),
        ),
    ]
