# Generated by Django 4.2.3 on 2023-10-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qaDatasetApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qadataset',
            name='flags',
            field=models.BooleanField(default=False),
        ),
    ]
